query getGraphs($input: GenerateGraphsRequest!) {
  getGraphs(input: $input) {
    totalEmissions{
      emisionTotal,
      unidadMedida
    },
    totalEmissionsByAlcance{
      alcance1{
        totalPorAlcance{
          emisionTotal,
          unidadMedida
        },
        emisionesPorUnidad{
          nombre,
          valor,
          unidadMedida
        },
        emisionesPorNivel2{
          nombre,
          valor,
          unidadMedida,
          area{
            nombre,
            valor,
            unidadMedida
          }
        }
      },
      alcance2{
        totalPorAlcance{
          emisionTotal,
          unidadMedida
        },
        emisionesPorUnidad{
          nombre,
          valor,
          unidadMedida
        },
        emisionesPorNivel2{
          nombre,
          valor,
          unidadMedida,
          area{
            nombre,
            valor,
            unidadMedida
          }
        }
      }
      alcance3{
        totalPorAlcance{
          emisionTotal,
          unidadMedida
        },
        emisionesPorUnidad{
          nombre,
          valor,
          unidadMedida
        },
        emisionesPorNivel2{
          nombre,
          valor,
          unidadMedida,
          area{
            nombre,
            valor,
            unidadMedida
          }
        }
}
}
}

}
